name = "text-adventure-ai"
account_id = "7d21a26d654a7c7812bd68be2f1b4ab4"
main = "build/server/index.js"
compatibility_date = "2026-03-10"
compatibility_flags = ["nodejs_compat"]

assets = { directory = "./build/client" }

[observability]
enabled = true

[[d1_databases]]
binding = "text_adventure_ai_db"
database_name = "text-adventure-ai-db"
database_id = "6641a8dd-e4df-4ddf-8695-fbcb4cb1bcec"

[[kv_namespaces]]
binding = "SESSION_CACHE"
id = "3b4e3445688245659813ca50d953ac21"
